- name: Configure Developer Infrastructure
  hosts: infra_vm
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - git
          - vim
          - curl
        state: present
        update_cache: yes

    - name: Create a new user 'infra_user'
      user:
        name: infra_user
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash

    - name: Set up SSH authorized key for infra_user
      authorized_key:
        user: infra_user
        state: present
        key: "{{ lookup('file', '~/.ssh/infra-key.pub') }}"
