- name: Configure Developer Infrastructure on Ubuntu EC2
  hosts: infra_vm
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - git
          - vim
          - curl
          - nodejs
        state: present