- name: Configure Developer Infrastructure on Ubuntu EC2
  hosts: infra_vm
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - git
          - vim
          - curl
        state: present

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Set JAVA_HOME in /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
        create: yes
        state: present

    - name: Update alternatives for java
      command: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      args:
        warn: false

    - name: Update alternatives for javac
      command: update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
      args:
        warn: false

    - name: Reload environment variables
      shell: . /etc/environment && export
      args:
        executable: /bin/bash
      changed_when: false
